# 서버 포트 설정

#server:
#  port: 3306

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wonbeen_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: wonbeen
    password: 1234
  thymeleaf:
    cache: false
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.MySQLInnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug
